### ISSUE TITLE
Color scheme & color palette

### ISSUE THREAD

**Issue by nisaury** [snappy-turtle/img-sharing-webapp#10]
Choose two primary colors to use for the design of the application.

**Comment by yurixander** [comment]
* We will be choosing primary colors. Avoid using yellow or red as a primary color.

* The primary colors should complement each other and not be opposites (ex. if green is chosen, the other one shouldn't be red).
* Black, gray, and white will be used alongside those primary colors.

We can use the following tools for inspiration:
1. https://flatuicolors.com/
2. https://coolors.co/

**Comment by KennNguyen** [comment]
We will be going with a light theme mode for this webpage, but when we have everything set, we will start developing the dark theme mode. Moreover, we will choose colors and styles that fit the theme of trendy, flat, minimalism, and modern. Furthermore, with color theory in the sense of designing a website, use appropriate colors to evoke certain emotions. For example, blue for calmness, or red, yellow, and orange for alertness.

**Comment by yurixander** [comment]
We have chosen the color palette for the project:

* Primary: `#9293fb`
* Off-white: `#F8F8F8`
* White: `#FFFFFF`
* Text: `#282947`
* Black: `#0A0A0A`

![image](https://github.com/snappy-turtle/img-sharing-webapp/assets/101931215/9bc97782-1640-4ba4-be01-f4b8111b5e98)
