### ISSUE TITLE
Choose a programming language for the backend

### ISSUE THREAD

**Issue by nisaury** [snappy-turtle/img-sharing-webapp#5]

**Comment by yurixander** [comment]
I would suggest picking the most appropriate language from the following list, which are all well-equipped for this project: Go, Node.js (JavaScript or TypeScript), or Python.

As per how to choose which, try asking GPT about their differences and when/where you would use one over the other.

**Comment by lucianoscarpaci** [comment]
Node.js with express, or another framework that might be faster than express. Do you have experience with fast frameworks that might be better than express?

**Comment by yurixander** [comment]
> Node.js with express, or another framework that might be faster than express. Do you have experience with fast frameworks that might be better than express?

I think Express should be performant enough for this project. Regardless, I don't think high-performance would be this specific project's critical focus.

**Comment by yurixander** [comment]
Ruby and the rails framework has been chosen.
