### ISSUE TITLE
Which UI library and why?

### ISSUE THREAD

**Issue by nisaury** [snappy-turtle/img-sharing-webapp#8]

**Comment by KennNguyen** [comment]
I believe React would be perfect for this project due to its simplicity from its component-based architecture, use of its virtual DOM which allows for better performance, and in the case we need to integrate other tools and frameworks, React is flexible, as well as being scalable.

**Comment by yurixander** [comment]
> I believe React would be perfect for this project due to its simplicity from its component-based architecture, use of its virtual DOM which allows for better performance, and in the case we need to integrate other tools and frameworks, React is flexible, as well as being scalable.

I agree with your reasoning, and as a bonus, I am most experienced with React, so it would be more efficient in terms of implementation time for me. So React it is.
